# Generated by Django 5.0.4 on 2024-05-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='academy',
            name='contact_number',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='academy',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='email_address',
            field=models.EmailField(default=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='academy',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='academy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_teacher', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.academy')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('national_identity_number', models.CharField(max_length=13)),
                ('roll_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_contact_number', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('fee_amount', models.FloatField()),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.class')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('awarded_by', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online Payment', 'Online Payment')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('fee_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student')),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('class_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='academy.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='academy.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Present', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('attendance_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obtained_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('day_name', models.CharField(max_length=20)),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student')),
                ('test_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.class')),
            ],
        ),
    ]
