# Generated by Django 5.0.4 on 2024-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_academy_contact_no_remove_academy_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='academy',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
