# Generated by Django 5.0.4 on 2024-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_academy_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='email_address',
        ),
        migrations.AddField(
            model_name='academy',
            name='email',
            field=models.EmailField(default='ahsantariq0724@gmail.com', max_length=254),
        ),
    ]
