# Generated by Django 5.0.4 on 2024-05-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_remove_academy_email_address_academy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='logo',
        ),
    ]
