# Generated by Django 5.0.4 on 2024-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_remove_academy_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
